name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Firebase

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Debug thư mục hiện tại
    - name: Debug current directory
      run: |
        pwd
        ls -la

    # 3. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 4. Tạo environment.ts
    - name: Create environment.ts
      env:
        FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
        FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      run: |
        # Tạo thư mục và kiểm tra
        mkdir -p src/environments
        ls -la src/environments
        
        # Tạo file environment.ts
        cat > src/environments/environment.ts << EOL
        export const environment = {
          production: true,
          firebase: {
            apiKey: '${FIREBASE_API_KEY}',
            authDomain: '${FIREBASE_AUTH_DOMAIN}',
            databaseURL: '${FIREBASE_DATABASE_URL}',
            projectId: '${FIREBASE_PROJECT_ID}',
            storageBucket: '${FIREBASE_STORAGE_BUCKET}',
            messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
            appId: '${FIREBASE_APP_ID}'
          }
        };
        EOL
        
        # Kiểm tra nội dung file
        echo "Checking environment.ts content:"
        cat src/environments/environment.ts

    # 5. Install dependencies
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 6. Build Angular project
    - name: Build Angular project
      run: npm run build1

    # 7. Kiểm tra build output
    - name: Check build output
      run: |
        echo "Checking build output directory:"
        ls -la dist
      
    # 8. Deploy to Firebase
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase
      # uses: w9jds/firebase-action@v2.2.1
      # with:
      #   args: deploy --only hosting:projp21-17b04-2e509
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        echo "Starting Firebase deployment..."
        echo "Using Firebase Hosting target: projp21-17b04-2e509"
        echo "Checking Firebase token..."
        if [ -z "$FIREBASE_TOKEN" ]; then
          echo "Error: FIREBASE_TOKEN is not set or is empty."
          exit 1
        else
          echo "FIREBASE_TOKEN is set and starts with: ${FIREBASE_TOKEN:0:10}..."
        fi

        echo "Running Firebase deploy command..."
        firebase deploy --only hosting:projp21-17b04-2e509

        echo "Firebase deployment completed. Checking deployment status..."
        firebase hosting:sites:list
