name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Triển khai khi có thay đổi trên nhánh `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Firebase # Liên kết với Environment "Firebase"

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Tạo environment.ts
    - name: Create environment.ts
      env:
        FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
        FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      run: |
        mkdir -p src/environments # Tạo thư mục nếu chưa tồn tại
        echo "export const environment = {" > src/environments/environment.ts
        echo "  production: true," >> src/environments/environment.ts
        echo "  firebase: {" >> src/environments/environment.ts
        echo "    apiKey: '${FIREBASE_API_KEY}'," >> src/environments/environment.ts
        echo "    authDomain: '${FIREBASE_AUTH_DOMAIN}'," >> src/environments/environment.ts
        echo "    databaseURL: '${FIREBASE_DATABASE_URL}'," >> src/environments/environment.ts
        echo "    projectId: '${FIREBASE_PROJECT_ID}'," >> src/environments/environment.ts
        echo "    storageBucket: '${FIREBASE_STORAGE_BUCKET}'," >> src/environments/environment.ts
        echo "    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}'," >> src/environments/environment.ts
        echo "    appId: '${FIREBASE_APP_ID}'" >> src/environments/environment.ts
        echo "  }" >> src/environments/environment.ts
        echo "};"

    # 3. Verify environment.ts
    - name: Verify environment.ts
      run: |
        if [ ! -f src/environments/environment.ts ]; then
          echo "File src/environments/environment.ts does not exist. Stopping workflow."
          exit 1
        fi
        
        # Đọc nội dung file environment.ts
        content=$(cat src/environments/environment.ts)
        
        # Kiểm tra cấu trúc của environment.firebase
        if ! echo "$content" | grep -q "firebase:"; then
          echo "Property 'firebase' is missing in environment.ts"
          exit 1
        fi
        
        # Kiểm tra các thuộc tính bắt buộc của firebase configuration
        required_props=("apiKey" "authDomain" "projectId" "storageBucket" "messagingSenderId" "appId")
        for prop in "${required_props[@]}"; do
          if ! echo "$content" | grep -q "$prop:"; then
            echo "Required property '$prop' is missing in environment.firebase"
            exit 1
          fi
        done
        
        echo "environment.ts structure verified successfully!"

    # 4. Debug Environment Variables
    - name: Debug Environment Variables
      env:
        FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
      run: |
        echo "FIREBASE_API_KEY=${FIREBASE_API_KEY}"

    # 5. Thiết lập Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Sử dụng phiên bản Node.js phù hợp với Angular

    # 6. Cài đặt các phụ thuộc
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 7. Build dự án Angular
    - name: Build Angular project
      run: npm run build1
      
    # 8. Đăng nhập Firebase CLI
    - name: Firebase CLI Login
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: login:ci
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    # 8.1. Debug Firebase Token
    - name: Debug Firebase Token
      run: |
        if [ -n "$FIREBASE_TOKEN" ]; then
          echo "FIREBASE_TOKEN is set and starts with: ${FIREBASE_TOKEN:0:10}..."
        else
          echo "FIREBASE_TOKEN is not set"
        fi
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    # 9. Triển khai lên Firebase Hosting
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: deploy --only hosting:projp21-17b04-2e509
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
