name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Triển khai khi có thay đổi trên nhánh `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Firebase # Liên kết với Environment "Firebase"

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Sử dụng phiên bản Node.js phù hợp với Angular

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 4. Build Angular project
    - name: Build Angular project
      run: npm run build1

    # 5. Kiểm tra build output
    - name: Check build output
      run: |
        echo "Checking build output directory:"
        ls -la dist/gitlabissue

    # 6. Deploy to Firebase
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: deploy --only hosting:projp21-17b04-2e509
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
