name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Triển khai khi có thay đổi trên nhánh `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Firebase # Liên kết với Environment "Firebase"

    steps:
    # 1. Tạo environment.ts
    - name: Create environment.ts
      env:
        FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
        FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      run: |
        mkdir -p src/environments # Tạo thư mục nếu chưa tồn tại
        echo "export const environment = {" > src/environments/environment.ts
        echo "  production: true," >> src/environments/environment.ts
        echo "  firebase: {" >> src/environments/environment.ts
        echo "    apiKey: '${FIREBASE_API_KEY}'," >> src/environments/environment.ts
        echo "    authDomain: '${FIREBASE_AUTH_DOMAIN}'," >> src/environments/environment.ts
        echo "    databaseURL: '${FIREBASE_DATABASE_URL}'," >> src/environments/environment.ts
        echo "    projectId: '${FIREBASE_PROJECT_ID}'," >> src/environments/environment.ts
        echo "    storageBucket: '${FIREBASE_STORAGE_BUCKET}'," >> src/environments/environment.ts
        echo "    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}'," >> src/environments/environment.ts
        echo "    appId: '${FIREBASE_APP_ID}'" >> src/environments/environment.ts
        echo "  }" >> src/environments/environment.ts
        echo "};"

    # 2. Debug Environment Variables
    - name: Debug Environment Variables
      env:
        FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
      run: |
        echo "FIREBASE_API_KEY=${FIREBASE_API_KEY}"

    # 3. Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # 4. Thiết lập Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Sử dụng phiên bản Node.js phù hợp với Angular

    # 5. Cài đặt các phụ thuộc
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 6. Build dự án Angular
    - name: Build Angular project
      run: npm run build -- --configuration production

    # 7. Đăng nhập Firebase CLI
    - name: Firebase CLI Login
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: login:ci
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Token Firebase được lưu trong GitHub Secrets

    # 8. Triển khai lên Firebase Hosting
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: deploy --only hosting:projp21-17b04-2e509
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
